// Package globaldefaults loads per-stack default bundles at boot.
//
// Bundles live at services/memory-router/global_defaults/<stack>.json,
// generated by infra/oss-corpus-bootstrap. Load is one-shot at startup;
// the in-memory cache is what the router serves from.
package globaldefaults

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"sync"

	memoryspec "github.com/crucible/memory-spec/go"
)

// Loader caches loaded bundles by stack id. Safe for concurrent reads
// after load.
type Loader struct {
	mu      sync.RWMutex
	bundles map[memoryspec.Stack]memoryspec.PerStackBundle
	// loaded is set once LoadAll has finished. Reads taken before this
	// is true return empty (matches "fresh tenant before bundle pulled").
	loaded bool
}

// NewLoader constructs an empty Loader.
func NewLoader() *Loader {
	return &Loader{bundles: map[memoryspec.Stack]memoryspec.PerStackBundle{}}
}

// LoadAll walks the given directory and loads every *.json file whose
// name matches a known Stack. Files that fail Validate are skipped with
// a non-fatal error; the rest still load. Returns the count loaded and
// any per-file errors aggregated.
func (l *Loader) LoadAll(dir string) (int, []error) {
	var errs []error
	count := 0
	known := map[string]memoryspec.Stack{}
	for _, s := range memoryspec.AllStacks() {
		known[string(s)] = s
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			// Fresh dev environment without bundles. Acceptable —
			// router runs in "no defaults" mode.
			l.mu.Lock()
			l.loaded = true
			l.mu.Unlock()
			return 0, []error{fmt.Errorf("global_defaults dir %q does not exist (running with no defaults)", dir)}
		}
		return 0, []error{err}
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".json") {
			continue
		}
		stem := strings.TrimSuffix(name, ".json")
		stack, ok := known[stem]
		if !ok {
			continue
		}
		path := filepath.Join(dir, name)
		bundle, err := loadOne(path)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", name, err))
			continue
		}
		if bundle.Stack != stack {
			errs = append(errs, fmt.Errorf("%s: stack mismatch (filename says %q, bundle says %q)", name, stack, bundle.Stack))
			continue
		}
		if err := bundle.Validate(); err != nil {
			errs = append(errs, fmt.Errorf("%s: validate: %w", name, err))
			continue
		}
		l.mu.Lock()
		l.bundles[stack] = bundle
		l.mu.Unlock()
		count++
	}
	l.mu.Lock()
	l.loaded = true
	l.mu.Unlock()
	return count, errs
}

func loadOne(path string) (memoryspec.PerStackBundle, error) {
	f, err := os.Open(path)
	if err != nil {
		return memoryspec.PerStackBundle{}, err
	}
	defer f.Close()
	raw, err := io.ReadAll(f)
	if err != nil {
		return memoryspec.PerStackBundle{}, err
	}
	var b memoryspec.PerStackBundle
	if err := json.Unmarshal(raw, &b); err != nil {
		return memoryspec.PerStackBundle{}, err
	}
	return b, nil
}

// ConventionsForStacks returns the union of active conventions across
// every requested stack. Used at fresh-tenant provisioning + on every
// recall for the global_defaults layer.
func (l *Loader) ConventionsForStacks(stacks ...memoryspec.Stack) []memoryspec.Convention {
	l.mu.RLock()
	defer l.mu.RUnlock()
	out := make([]memoryspec.Convention, 0, 256)
	for _, s := range stacks {
		b, ok := l.bundles[s]
		if !ok {
			continue
		}
		for _, c := range b.Conventions {
			if c.Status != memoryspec.StatusActive && c.Status != memoryspec.StatusSuggested {
				continue
			}
			c.Layer = memoryspec.LayerGlobalDefaults
			c.TenantID = "global"
			out = append(out, c)
		}
	}
	return out
}

// Stacks returns the stacks the loader has bundles for.
func (l *Loader) Stacks() []memoryspec.Stack {
	l.mu.RLock()
	defer l.mu.RUnlock()
	out := make([]memoryspec.Stack, 0, len(l.bundles))
	for s := range l.bundles {
		out = append(out, s)
	}
	return out
}

// Stats returns per-stack rule counts for the loader's bundles.
// Surfaced in the PHASE-5-REPORT.
func (l *Loader) Stats() map[memoryspec.Stack]int {
	l.mu.RLock()
	defer l.mu.RUnlock()
	out := make(map[memoryspec.Stack]int, len(l.bundles))
	for s, b := range l.bundles {
		n := 0
		for _, c := range b.Conventions {
			if c.Status == memoryspec.StatusActive {
				n++
			}
		}
		out[s] = n
	}
	return out
}
