module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "control-plane",
        "twin-runtime",
        "verifier",
        "distiller",
        "promotion-gate",
        "cli",
        "web-console",
        "ide-plugins",
        "sdk-go",
        "sdk-ts",
        "sdk-py",
        "sdk-rs",
        "attestation",
        "twin-spec",
        "memory-spec",
        "tape-format",
        "policy",
        "model-routing",
        "verifiers",
        "infra",
        "examples",
        "docs",
        "scripts",
        "ci",
        "release",
      ],
    ],
    "subject-case": [0],
  },
};
