//! mitmproxy addon renderer — solo-founder / E2B-tier enforcement.
//!
//! Per the May 2026 currency check:
//!
//! - mitmproxy's `allow_hosts` controls **which hosts get MITM'd**, not
//!   which hosts are permitted egress — we must drop in a
//!   `tls_clienthello` addon.
//! - The `tls.ClientHelloData.context.client.error` field is the right
//!   primitive for an actual drop (versus `ignore_connection = True` which
//!   passes through unmodified).
//! - HTTP/3 / QUIC is unsupported in regular-proxy mode (CONNECT is TCP).
//!   We accept that and document it.

use crucible_sandbox_spec::EgressManifest;

/// Render the Python addon source for a mitmproxy instance enforcing
/// `manifest`. Output is deterministic so the spec_hash includes it.
///
/// The addon binds the allowlist at import time. The runtime writes the
/// rendered file to a path inside the sandbox; mitmdump is started with
/// `mitmdump --mode transparent --set web_password=<random> -s <addon-path>`.
#[must_use]
pub fn render_addon(manifest: &EgressManifest) -> String {
    let mut allowed: Vec<&str> = manifest.rules.iter().map(|r| r.host.as_str()).collect();
    allowed.sort_unstable();
    allowed.dedup();
    let allow_list = allowed
        .iter()
        .map(|h| format!("    \"{}\",", py_escape(h)))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "# Auto-generated by twin-runtime-egress::mitmproxy::render_addon.\n\
         # Phase 2 — Crucible Twin Runtime.\n\
         from mitmproxy import tls, ctx\n\
         \n\
         ALLOWLIST = {{\n{allow_list}\n}}\n\
         \n\
         class CrucibleEgressGuard:\n\
         \    def tls_clienthello(self, data: tls.ClientHelloData):\n\
         \        sni = (data.client_hello.sni or \"\").lower()\n\
         \        if sni in ALLOWLIST:\n\
         \            return\n\
         \        ctx.log.warn(f\"egress denied SNI={{sni!r}}\")\n\
         \        # tls_clienthello has no direct \"drop\" verb; we mark the\n\
         \        # client context with an error message and let the proxy\n\
         \        # terminate.  See May 2026 currency check.\n\
         \        data.context.client.error = f\"crucible egress denied: {{sni}}\"\n\
         \n\
         \    def http_connect(self, flow):\n\
         \        host = flow.request.host.lower() if flow.request else \"\"\n\
         \        if host not in ALLOWLIST:\n\
         \            ctx.log.warn(f\"egress denied CONNECT host={{host!r}}\")\n\
         \            flow.kill()\n\
         \n\
         addons = [CrucibleEgressGuard()]\n",
    )
}

fn py_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crucible_sandbox_spec::{DefaultEgressAction, EgressDisposition, EgressRule};

    fn manifest(hosts: &[&str]) -> EgressManifest {
        EgressManifest {
            rules: hosts
                .iter()
                .map(|h| EgressRule {
                    host: (*h).into(),
                    ports: vec![443],
                    disposition: EgressDisposition::Allow,
                    tape_only: false,
                    justification: "test".into(),
                })
                .collect(),
            default_action: DefaultEgressAction::Deny,
        }
    }

    #[test]
    fn empty_manifest_renders_empty_allowlist() {
        let yaml = render_addon(&EgressManifest::deny_all());
        assert!(yaml.contains("ALLOWLIST = {"));
        assert!(yaml.contains("class CrucibleEgressGuard"));
        assert!(yaml.contains("tls_clienthello"));
        assert!(yaml.contains("http_connect"));
    }

    #[test]
    fn render_is_deterministic() {
        let m = manifest(&["api.stripe.com", "api.openai.com"]);
        assert_eq!(render_addon(&m), render_addon(&m));
    }

    #[test]
    fn rendered_addon_lists_hosts_sorted() {
        let m = manifest(&["b.example.com", "a.example.com"]);
        let py = render_addon(&m);
        let a = py.find("a.example.com").expect("a in output");
        let b = py.find("b.example.com").expect("b in output");
        assert!(a < b, "hosts should be sorted in deterministic order");
    }

    #[test]
    fn quotes_escaped_in_host_name() {
        // While shouldn't happen for valid manifest, defense-in-depth.
        let m = manifest(&["weird\"host"]);
        let py = render_addon(&m);
        assert!(py.contains("weird\\\"host"));
    }
}
