// Package cruciblev1 is the hand-rolled Phase-1 equivalent of the protobuf
// code that would be generated by `buf generate` against
// libs/twin-spec/proto/crucible/v1/*.proto.
//
// Every type here mirrors a proto message. JSON tags use snake_case so the
// in-toto predicates serialize to the same shape as the JSON Schemas in
// libs/twin-spec/schemas/. Once Phase 2 wires buf into CI, these types will
// be regenerated; the test suite asserts the hand-rolled equivalents stay in
// sync with the proto definitions.
package cruciblev1

import "time"

// ── enums ─────────────────────────────────────────────────────────────────

type Action string

const (
	ActionAdd    Action = "add"
	ActionModify Action = "modify"
	ActionDelete Action = "delete"
)

type Complexity string

const (
	ComplexityTrivial       Complexity = "trivial"
	ComplexityStandard      Complexity = "standard"
	ComplexityComplex       Complexity = "complex"
	ComplexityCritical      Complexity = "critical"
	ComplexityModernization Complexity = "modernization"
)

type ModelTier int

const (
	ModelTier0 ModelTier = 0
	ModelTier1 ModelTier = 1
	ModelTier2 ModelTier = 2
	ModelTier3 ModelTier = 3
	ModelTier4 ModelTier = 4
)

type Reversibility string

const (
	ReversibilityTrivial      Reversibility = "trivial"
	ReversibilitySnapshot     Reversibility = "snapshot"
	ReversibilityLossy        Reversibility = "lossy"
	ReversibilityIrreversible Reversibility = "irreversible"
)

type TaskStatus string

const (
	TaskStatusReceived            TaskStatus = "received"
	TaskStatusPlanning            TaskStatus = "planning"
	TaskStatusAwaitingApproval    TaskStatus = "awaiting_approval"
	TaskStatusApproved            TaskStatus = "approved"
	TaskStatusRejected            TaskStatus = "rejected"
	TaskStatusExecuting           TaskStatus = "executing"
	TaskStatusVerifying           TaskStatus = "verifying"
	TaskStatusPromoting           TaskStatus = "promoting"
	TaskStatusLanded              TaskStatus = "landed"
	TaskStatusRolledBack          TaskStatus = "rolled_back"
	TaskStatusBudgetExceeded      TaskStatus = "budget_exceeded"
	TaskStatusRetryLimitExceeded  TaskStatus = "retry_limit_exceeded"
	TaskStatusWallClockExceeded   TaskStatus = "wall_clock_exceeded"
	TaskStatusFailed              TaskStatus = "failed"
)

type ErrorCode string

const (
	ErrBudgetExceeded             ErrorCode = "BudgetExceeded"
	ErrRetryLimitExceeded         ErrorCode = "RetryLimitExceeded"
	ErrWallClockExceeded          ErrorCode = "WallClockExceeded"
	ErrEgressDenied               ErrorCode = "EgressDenied"
	ErrSecretAccessDenied         ErrorCode = "SecretAccessDenied"
	ErrDestructiveProposalReject  ErrorCode = "DestructiveProposalRejected"
	ErrTwinSetupError             ErrorCode = "TwinSetupError"
	ErrTapeIntegrityError         ErrorCode = "TapeIntegrityError"
	ErrVerifierRejection          ErrorCode = "VerifierRejection"
	ErrPromotionPolicyDenied      ErrorCode = "PromotionPolicyDenied"
	ErrApprovalTimeout            ErrorCode = "ApprovalTimeout"
	ErrCanaryRollback             ErrorCode = "CanaryRollback"
	ErrTenantQuotaExceeded        ErrorCode = "TenantQuotaExceeded"
	ErrModelRoutingDenied         ErrorCode = "ModelRoutingDenied"
)

// ── common ─────────────────────────────────────────────────────────────────

type Glob struct {
	Pattern string `json:"pattern"`
}

type ScopeFilter struct {
	Repo     string `json:"repo,omitempty"`
	FileGlob string `json:"file_glob,omitempty"`
	Category string `json:"category,omitempty"`
}

// Scope is the union { all | filter }. Encode "all" as the literal string "all"
// in JSON; otherwise emit the filter object.
type Scope struct {
	All    bool         `json:"-"`
	Filter *ScopeFilter `json:"-"`
}

type FileChange struct {
	Path          string `json:"path"`
	Action        Action `json:"action"`
	Content       string `json:"content,omitempty"`
	ContentSha256 string `json:"content_sha256,omitempty"`
	SizeBytes     uint64 `json:"size_bytes,omitempty"`
}

type Diff struct {
	Files   []FileChange `json:"files"`
	BaseSha string       `json:"base_sha,omitempty"`
}

type SourceRefKind string

const (
	SourceRefPrComment        SourceRefKind = "pr_comment"
	SourceRefIncident         SourceRefKind = "incident"
	SourceRefAdr              SourceRefKind = "adr"
	SourceRefAgentObservation SourceRefKind = "agent_observation"
)

type SourceRef struct {
	Kind             SourceRefKind `json:"kind"`
	PR               uint64        `json:"pr,omitempty"`
	CommentID        string        `json:"comment_id,omitempty"`
	IncidentID       string        `json:"id,omitempty"`
	Service          string        `json:"service,omitempty"`
	AdrPath          string        `json:"path,omitempty"`
	AdrCommit        string        `json:"commit,omitempty"`
	ObservationTask  string        `json:"task_id,omitempty"`
	ObservationStep  string        `json:"step_id,omitempty"`
}

type SecretRef struct {
	Name      string    `json:"name"`
	Handle    string    `json:"handle"`
	ExpiresAt time.Time `json:"expires_at,omitempty"`
}

type ExecResult struct {
	Stdout              string `json:"stdout"`
	Stderr              string `json:"stderr"`
	ExitCode            int32  `json:"exit_code"`
	DurationMs          uint64 `json:"duration_ms"`
	SignedAttestation   string `json:"signed_attestation,omitempty"`
}

type BlastRadius struct {
	AffectedResources []string      `json:"affected_resources"`
	Reversibility     Reversibility `json:"reversibility"`
	ImpactScore       float64       `json:"impact_score"`
}

type DestructiveProposal struct {
	TaskID                 string       `json:"task_id"`
	TenantID               string       `json:"tenant_id"`
	Command                string       `json:"command"`
	Scope                  string       `json:"scope"`           // "twin" | "real"
	Justification          string       `json:"justification,omitempty"`
	BlastRadius            BlastRadius  `json:"blast_radius"`
	JustificationRequired  bool         `json:"justification_required"`
	InterceptedAtLayer     string       `json:"intercepted_at_layer"`
	ProposedAt             time.Time    `json:"proposed_at"`
	AgentOidcSubject       string       `json:"agent_oidc_subject"`
}

type ExternalEffect struct {
	Service   string   `json:"service"`
	Endpoints []string `json:"endpoints"`
	Live      bool     `json:"live"`
}

type Risk struct {
	Description string `json:"description"`
	Impact      string `json:"impact"` // "low" | "medium" | "high"
}

// ── task / plan ─────────────────────────────────────────────────────────────

type Task struct {
	ID             string     `json:"id"`
	TenantID       string     `json:"tenant_id"`
	Repo           string     `json:"repo"`
	BaseSha        string     `json:"base_sha"`
	Description    string     `json:"description"`
	Status         TaskStatus `json:"status"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	SubmittedBy    string     `json:"submitted_by"`
	Plan           *Plan      `json:"plan,omitempty"`
	Routing        *Routing   `json:"routing,omitempty"`
	Budget         *Budget    `json:"budget,omitempty"`
	RelatedTaskIDs []string   `json:"related_task_ids,omitempty"`
}

type PlanStep struct {
	Ordinal       uint32 `json:"ordinal"`
	Description   string `json:"description"`
	RetryBudget   uint32 `json:"retry_budget"`
	RetriesUsed   uint32 `json:"retries_used"`
}

type Plan struct {
	TaskID                string           `json:"task_id"`
	Description           string           `json:"description"`
	Steps                 []PlanStep       `json:"steps"`
	EstimatedCostUsd      float64          `json:"estimated_cost_usd"`
	EstimatedDurationMin  uint32           `json:"estimated_duration_min"`
	FilesToTouch          []string         `json:"files_to_touch"`
	DbMigrations          uint32           `json:"db_migrations"`
	ExternalEffects       []ExternalEffect `json:"external_effects"`
	TopRisks              []Risk           `json:"top_risks"`
	RetryBudgetPerStep    uint32           `json:"retry_budget_per_step"`
	WallClockBudgetMin    uint32           `json:"wall_clock_budget_min"`
	Complexity            Complexity       `json:"complexity"`
	PlanHash              string           `json:"plan_hash"`
	BuiltAt               time.Time        `json:"built_at"`
}

type PlanApproval struct {
	TaskID              string    `json:"task_id"`
	PlanHash            string    `json:"plan_hash"`
	ApproverOidcSubject string    `json:"approver_oidc_subject"`
	ApprovedAt          time.Time `json:"approved_at"`
	AttestationID       string    `json:"attestation_id,omitempty"`
	CostCapUsd          float64   `json:"cost_cap_usd"`
	WallClockCapMin     uint32    `json:"wall_clock_cap_min"`
	RetryCapPerSubgoal  uint32    `json:"retry_cap_per_subgoal"`
}

type PlanRejection struct {
	TaskID              string    `json:"task_id"`
	PlanHash            string    `json:"plan_hash"`
	Reason              string    `json:"reason"`
	RejecterOidcSubject string    `json:"rejecter_oidc_subject"`
	RejectedAt          time.Time `json:"rejected_at"`
}

type Routing struct {
	ExecutorModel              string    `json:"executor_model"`
	ExecutorVendor             string    `json:"executor_vendor"`
	ExecutorTier               ModelTier `json:"executor_tier"`
	VerifierModel              string    `json:"verifier_model"`
	VerifierVendor             string    `json:"verifier_vendor"`
	VerifierTier               ModelTier `json:"verifier_tier"`
	CriticalScore              float64   `json:"critical_score"`
	IsCritical                 bool      `json:"is_critical"`
	DecidedAt                  time.Time `json:"decided_at"`
	ClassifierAttestationID    string    `json:"classifier_attestation_id,omitempty"`
}

type Budget struct {
	SpentUsd             float64 `json:"spent_usd"`
	CapUsd               float64 `json:"cap_usd"`
	StepsUsed            uint32  `json:"steps_used"`
	StepsCap             uint32  `json:"steps_cap"`
	WallClockUsedSeconds uint64  `json:"wall_clock_used_seconds"`
	WallClockCapSeconds  uint64  `json:"wall_clock_cap_seconds"`
	RetriesUsed          uint32  `json:"retries_used"`
	RetryCap             uint32  `json:"retry_cap"`
}

// ── memory ─────────────────────────────────────────────────────────────────

type ConventionStatus string

const (
	ConvActive     ConventionStatus = "active"
	ConvDrifting   ConventionStatus = "drifting"
	ConvSuperseded ConventionStatus = "superseded"
	ConvRejected   ConventionStatus = "rejected"
)

type Convention struct {
	ID                  string           `json:"id"`
	TenantID            string           `json:"tenant_id"`
	Scope               ScopeFilter      `json:"scope"`
	RuleNl              string           `json:"rule_nl"`
	Category            string           `json:"category"`
	Status              ConventionStatus `json:"status"`
	Confidence          float64          `json:"confidence"`
	JudgeScore          float64          `json:"judge_score"`
	SourceEvidence      []SourceRef      `json:"source_evidence,omitempty"`
	ValidFrom           time.Time        `json:"valid_from"`
	ValidTo             *time.Time       `json:"valid_to,omitempty"`
	Supersedes          string           `json:"supersedes,omitempty"`
	WriterOidcSubject   string           `json:"writer_oidc_subject"`
	WrittenAt           time.Time        `json:"written_at"`
}

type MemoryKind string

const (
	MemHot        MemoryKind = "hot"
	MemEpisodic   MemoryKind = "episodic"
	MemSemantic   MemoryKind = "semantic"
	MemProcedural MemoryKind = "procedural"
)

type Memory struct {
	ID            string     `json:"id"`
	Content       string     `json:"content"`
	Importance    float64    `json:"importance"`
	WrittenAt     time.Time  `json:"written_at"`
	LastRecalled  time.Time  `json:"last_recalled"`
	Kind          MemoryKind `json:"kind"`
	Source        SourceRef  `json:"source"`
}

type ComplianceReport struct {
	DiffHash            string                       `json:"diff_hash"`
	Violations          []ComplianceReportViolation  `json:"violations"`
	ConventionsChecked  uint32                       `json:"conventions_checked"`
	GeneratedAt         time.Time                    `json:"generated_at"`
}

type ComplianceReportViolation struct {
	ConventionID  string `json:"convention_id"`
	RuleNl        string `json:"rule_nl"`
	OffendingFile string `json:"offending_file"`
	OffendingLine uint32 `json:"offending_line"`
	Snippet       string `json:"snippet"`
	Severity      string `json:"severity"` // "info" | "warn" | "error"
}

// ── verification ────────────────────────────────────────────────────────────

type Tier string

const (
	TierMutation   Tier = "tier_0_mutation"
	TierPBT        Tier = "tier_1_pbt"
	TierContract   Tier = "tier_2_contract"
	TierProof      Tier = "tier_3_proof"
	TierHonestCI   Tier = "tier_4_honest_ci"
)

type TierResult struct {
	Tier              Tier    `json:"tier"`
	Passed            bool    `json:"passed"`
	ReportAttestation string  `json:"report_attestation,omitempty"`
	Score             float64 `json:"score,omitempty"`
	Framework         string  `json:"framework,omitempty"`
	DurationSeconds   uint64  `json:"duration_seconds,omitempty"`
	Error             string  `json:"error,omitempty"`
}

type TierResults struct {
	Tier0 *TierResult `json:"tier_0,omitempty"`
	Tier1 *TierResult `json:"tier_1,omitempty"`
	Tier2 *TierResult `json:"tier_2,omitempty"`
	Tier3 *TierResult `json:"tier_3,omitempty"`
	Tier4 *TierResult `json:"tier_4,omitempty"`
}

type VerifierApproval struct {
	TaskID               string       `json:"task_id"`
	DiffHash             string       `json:"diff_hash"`
	Verdict              string       `json:"verdict"`        // always "approved"
	RubricScore          float64      `json:"rubric_score"`
	TierResults          TierResults  `json:"tier_results"`
	ExecutorOidcSubject  string       `json:"executor_oidc_subject"`
	VerifierOidcSubject  string       `json:"verifier_oidc_subject"`
	ExecutorModel        string       `json:"executor_model,omitempty"`
	VerifierModel        string       `json:"verifier_model,omitempty"`
	SignedAt             time.Time    `json:"signed_at"`
	AttestationID        string       `json:"attestation_id,omitempty"`
}

type RejectionReason struct {
	Category     string `json:"category"`
	Detail       string `json:"detail"`
	File         string `json:"file,omitempty"`
	Line         uint32 `json:"line,omitempty"`
	SuggestedFix string `json:"suggested_fix,omitempty"`
}

type VerifierRejection struct {
	TaskID              string            `json:"task_id"`
	DiffHash            string            `json:"diff_hash"`
	Verdict             string            `json:"verdict"`           // always "rejected"
	RejectionReasons    []RejectionReason `json:"rejection_reasons"`
	TierResults         TierResults       `json:"tier_results,omitempty"`
	ExecutorOidcSubject string            `json:"executor_oidc_subject"`
	VerifierOidcSubject string            `json:"verifier_oidc_subject"`
	SignedAt            time.Time         `json:"signed_at"`
	AttestationID       string            `json:"attestation_id,omitempty"`
}

type SuggestedRolloutStep struct {
	Weight        uint32 `json:"weight"`
	DwellSeconds  uint32 `json:"dwell_seconds"`
}

type SuggestedRollout struct {
	Steps                 []SuggestedRolloutStep `json:"steps"`
	DwellSecondsPerStep   uint32                 `json:"dwell_seconds_per_step,omitempty"`
	SloCheck              string                 `json:"slo_check,omitempty"`
}

type PromotionBundle struct {
	TaskID                       string           `json:"task_id"`
	DiffHash                     string           `json:"diff_hash"`
	VerifierApprovalAttestation  string           `json:"verifier_approval_attestation"`
	FilesChanged                 []FileChange     `json:"files_changed"`
	BuildProvenanceAttestation   string           `json:"build_provenance_attestation,omitempty"`
	RebuildHash                  string           `json:"rebuild_hash,omitempty"`
	BlastRadius                  BlastRadius      `json:"blast_radius"`
	SuggestedRollout             SuggestedRollout `json:"suggested_rollout"`
	AgentOidcSubject             string           `json:"agent_oidc_subject"`
	SignedAt                     time.Time        `json:"signed_at"`
	AttestationID                string           `json:"attestation_id,omitempty"`
}

type PromotionID struct {
	ID string `json:"id"`
}

type PromotionStatusKind string

const (
	PromotionPendingPolicy   PromotionStatusKind = "pending_policy"
	PromotionPendingApproval PromotionStatusKind = "pending_approval"
	PromotionApproved        PromotionStatusKind = "approved"
	PromotionDeploying       PromotionStatusKind = "deploying"
	PromotionCanaryDwell     PromotionStatusKind = "canary_dwell"
	PromotionLanded          PromotionStatusKind = "landed"
	PromotionRolledBack      PromotionStatusKind = "rolled_back"
	PromotionRejected        PromotionStatusKind = "rejected"
)

type PromotionStatus struct {
	ID         string              `json:"id"`
	Kind       PromotionStatusKind `json:"kind"`
	Detail     string              `json:"detail,omitempty"`
	UpdatedAt  time.Time           `json:"updated_at"`
}
