// Package inferred generates the "inferred AGENTS.md" markdown the
// customer reviews when their repo doesn't already have one.
//
// This is the fallback Stage-2 output for repos that don't carry a
// customer-authored AGENTS.md / CLAUDE.md / .cursorrules. The rules
// of this generator:
//
//   1. Be CONSERVATIVE. The customer reviews this file before
//      activation; we surface what we found, not what we infer should
//      be true.
//   2. Group by the 12-category taxonomy from
//      docs/06-research/memory-bootstrap.md.
//   3. Show provenance for every line — the customer needs to
//      understand whether a rule came from their lint config, their
//      ADR directory, or an OSS default.
//   4. Cap at ~60 rules. Beyond that, the customer can't review in a
//      reasonable session and they'll hit "approve all" without
//      thinking. We pick the highest-confidence rule per category.
package inferred

import (
	"fmt"
	"sort"
	"strings"

	"github.com/crucible/apps/cartographer/internal/types"
)

// Generate renders an AGENTS.md document.
func Generate(repo string, stackPrimary string, high, medium []types.ConventionCandidate) string {
	var sb strings.Builder
	sb.WriteString("# AGENTS.md\n\n")
	sb.WriteString("> Generated by Crucible Cartographer. Review and edit before activation.\n")
	sb.WriteString("> Source: ")
	sb.WriteString(repo)
	if stackPrimary != "" {
		sb.WriteString(" (stack: ")
		sb.WriteString(stackPrimary)
		sb.WriteString(")")
	}
	sb.WriteString("\n\n")
	sb.WriteString("This file documents conventions Crucible inferred from your codebase.\n")
	sb.WriteString("Customer-authored AGENTS.md / CLAUDE.md / .cursorrules at the repo root\n")
	sb.WriteString("always wins over the rules below; this file is the seed when none exists.\n\n")

	cands := make([]types.ConventionCandidate, 0, len(high)+len(medium))
	cands = append(cands, high...)
	cands = append(cands, medium...)
	if len(cands) == 0 {
		sb.WriteString("_No high-confidence conventions inferred from this repo. Crucible will\nstart from the OSS-derived defaults for your stack and learn as your\nteam reviews PRs._\n")
		return sb.String()
	}

	// Cap per category to keep the file reviewable.
	perCat := map[string][]types.ConventionCandidate{}
	for _, c := range cands {
		perCat[c.Category] = append(perCat[c.Category], c)
	}
	for k, v := range perCat {
		sort.SliceStable(v, func(i, j int) bool { return v[i].Confidence > v[j].Confidence })
		// Cap at 8 per category.
		if len(v) > 8 {
			v = v[:8]
		}
		perCat[k] = v
	}

	// Stable category order.
	order := []string{
		"Naming", "Layering", "Library preferences", "Test patterns",
		"Error handling", "Logging", "Migration patterns", "Concurrency",
		"PR/commit hygiene", "Security defaults", "Performance defaults",
		"API shape",
	}
	for _, cat := range order {
		v, ok := perCat[cat]
		if !ok || len(v) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "## %s\n\n", cat)
		for _, c := range v {
			provenance := provFor(c.SourceChannel, c.SourcePath)
			fmt.Fprintf(&sb, "- %s _(source: %s, confidence: %.2f)_\n", c.RuleNL, provenance, c.Confidence)
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n")
	sb.WriteString("**Next steps:**\n")
	sb.WriteString("1. Review each line. Edit, delete, or accept.\n")
	sb.WriteString("2. Commit this file as `AGENTS.md` at the repo root.\n")
	sb.WriteString("3. Crucible will treat your version as the authoritative override.\n")
	return sb.String()
}

func provFor(channel, path string) string {
	switch channel {
	case "lint_config":
		return "lint config: " + path
	case "adr_file":
		return "ADR: " + path
	case "agents_md":
		return "AGENTS.md: " + path
	case "contributing_md":
		return "CONTRIBUTING.md: " + path
	case "pr_comment":
		return "PR review: " + path
	case "incident":
		return "incident: " + path
	case "oss_default":
		return "OSS default for stack"
	}
	return channel
}
